"""add avatar_url banner_url to users_data

Revision ID: 1258cfb331ec
Revises: d6fea0b98873
Create Date: 2026-04-29 11:43:17.825012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1258cfb331ec'
down_revision: Union[str, Sequence[str], None] = 'd6fea0b98873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_data', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users_data', sa.Column('banner_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_data', 'banner_url')
    op.drop_column('users_data', 'avatar_url')
    # ### end Alembic commands ###
