"""adding date when user likes

Revision ID: 5c97825dadc3
Revises: 1258cfb331ec
Create Date: 2026-04-29 16:39:48.977486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c97825dadc3'
down_revision: Union[str, Sequence[str], None] = '1258cfb331ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_likes', sa.Column('liked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_likes', 'liked_at')
    # ### end Alembic commands ###
