"""add_email_and_refresh_tokens

Revision ID: d6fea0b98873
Revises: efe917dc7dcc
Create Date: 2026-04-24 13:21:54.502197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fea0b98873'
down_revision: Union[str, Sequence[str], None] = 'efe917dc7dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('users_data', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users_data', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_data', type_='unique')
    op.drop_column('users_data', 'email')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
